package com.nit.cj_exception_handling;

public class Try_Catch_Finally_Case4 {

	public static void main(String[] args) {
		
		try {
			System.out.println("In try");
		}finally {
			System.out.println("In finally");
		}
		System.out.println("after try/finally");
	}

}
